// Code generated by "enumer -type=Phase -linecomment -text -output controller_enums.go"; DO NOT EDIT.

package session

import (
	"fmt"
	"strings"
)

const _PhaseName = "idleconnectingconnectedreconnectingdisconnectedauth_failedother_sessionlocal_session_blockedrebootingfatal_error"

var _PhaseIndex = [...]uint8{0, 4, 14, 23, 35, 47, 58, 71, 92, 101, 112}

const _PhaseLowerName = "idleconnectingconnectedreconnectingdisconnectedauth_failedother_sessionlocal_session_blockedrebootingfatal_error"

func (i Phase) String() string {
	if i >= Phase(len(_PhaseIndex)-1) {
		return fmt.Sprintf("Phase(%d)", i)
	}
	return _PhaseName[_PhaseIndex[i]:_PhaseIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PhaseNoOp() {
	var x [1]struct{}
	_ = x[PhaseIdle-(0)]
	_ = x[PhaseConnecting-(1)]
	_ = x[PhaseConnected-(2)]
	_ = x[PhaseReconnecting-(3)]
	_ = x[PhaseDisconnected-(4)]
	_ = x[PhaseAuthFailed-(5)]
	_ = x[PhaseOtherSession-(6)]
	_ = x[PhaseLocalSessionBlocked-(7)]
	_ = x[PhaseRebooting-(8)]
	_ = x[PhaseFatal-(9)]
}

var _PhaseValues = []Phase{PhaseIdle, PhaseConnecting, PhaseConnected, PhaseReconnecting, PhaseDisconnected, PhaseAuthFailed, PhaseOtherSession, PhaseLocalSessionBlocked, PhaseRebooting, PhaseFatal}

var _PhaseNameToValueMap = map[string]Phase{
	_PhaseName[0:4]:          PhaseIdle,
	_PhaseLowerName[0:4]:     PhaseIdle,
	_PhaseName[4:14]:         PhaseConnecting,
	_PhaseLowerName[4:14]:    PhaseConnecting,
	_PhaseName[14:23]:        PhaseConnected,
	_PhaseLowerName[14:23]:   PhaseConnected,
	_PhaseName[23:35]:        PhaseReconnecting,
	_PhaseLowerName[23:35]:   PhaseReconnecting,
	_PhaseName[35:47]:        PhaseDisconnected,
	_PhaseLowerName[35:47]:   PhaseDisconnected,
	_PhaseName[47:58]:        PhaseAuthFailed,
	_PhaseLowerName[47:58]:   PhaseAuthFailed,
	_PhaseName[58:71]:        PhaseOtherSession,
	_PhaseLowerName[58:71]:   PhaseOtherSession,
	_PhaseName[71:92]:        PhaseLocalSessionBlocked,
	_PhaseLowerName[71:92]:   PhaseLocalSessionBlocked,
	_PhaseName[92:101]:       PhaseRebooting,
	_PhaseLowerName[92:101]:  PhaseRebooting,
	_PhaseName[101:112]:      PhaseFatal,
	_PhaseLowerName[101:112]: PhaseFatal,
}

var _PhaseNames = []string{
	_PhaseName[0:4],
	_PhaseName[4:14],
	_PhaseName[14:23],
	_PhaseName[23:35],
	_PhaseName[35:47],
	_PhaseName[47:58],
	_PhaseName[58:71],
	_PhaseName[71:92],
	_PhaseName[92:101],
	_PhaseName[101:112],
}

// PhaseString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PhaseString(s string) (Phase, error) {
	if val, ok := _PhaseNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PhaseNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Phase values", s)
}

// PhaseValues returns all values of the enum
func PhaseValues() []Phase {
	return _PhaseValues
}

// PhaseStrings returns a slice of all String values of the enum
func PhaseStrings() []string {
	strs := make([]string, len(_PhaseNames))
	copy(strs, _PhaseNames)
	return strs
}

// IsAPhase returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Phase) IsAPhase() bool {
	for _, v := range _PhaseValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for Phase
func (i Phase) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Phase
func (i *Phase) UnmarshalText(text []byte) error {
	var err error
	*i, err = PhaseString(string(text))
	return err
}
